const ConnectionStatusBar = ({
  obsConnected,
  youtubeSignedIn,
  youtubeUser,
  loading,
  performers,
  activeIntermission,
  cardStyle,
  buttonStyle,
  secondaryButtonStyle,
  onObsDisconnect,
  onShowObsConnect,
  onYoutubeSignOut,
  onShowYoutubeLogin,
  onCreateIntermissionScenes,
  onStartIntermission,
  onCreateSongBroadcasts,
  onCreateUpNextScene,
  fetchPerformers,
  loadBroadcasts
}) => {